### ISSUE TITLE
plugin doesn't work at all when using live preview

### ISSUE THREAD

**Issue by youcefs21** [deathau/cm-typewriter-scroll-obsidian#23]
the plugin only works in legacy mode.

**Comment by frankreporting** [comment]
Fwiw the developer very much seems to be working on an update that could work with Live Preview. There's a long discussion on Obsidian's Discord server about it. No clue as to ETA but I'm also excited for this update.

**Comment by kergma-lw** [comment]
Are there some news?

**Comment by ananthuthilakan** [comment]
me tooo

**Comment by kassirh** [comment]
This is one of the best plugins around. Fingers crossed! And thank you for creating the plugin.

**Comment by fuckgfwfuckfuck** [comment]
@deathau Could you update this plugin to fit in live preview? This plugin is so amazing that I can't wait to use it by a new version of Obsidian.

**Comment by Ellipsine** [comment]
Thank you very much for updating it, it works fine ! :)
