### ISSUE TITLE
New Version need reload to turn off 

### ISSUE THREAD

**Issue by tim-hilde** [deathau/cm-typewriter-scroll-obsidian#26]
With the new LP update I need to reload Obsidian to toggle off the scrolling feature.

**Comment by oldjove** [comment]
Any chance this could be addressed? I love using this plugin for longform writing, but the need to reload to turn it off is a bit annoying.

**Comment by icheft** [comment]
Agreed on this one. Any updates so far? 

Thanks for the plugin anyway!

**Comment by hakusaro** [comment]
@deathau hi! I'd be more than happy to sponsor you for an update to this plugin to fix the issues with not being able to turn it off/on properly. Are you interested?

**Comment by deathau** [comment]
I'm kinda stuck with this at the moment. It currently works as a CM6 extension, and I can _register_ the CM6 extension, but I can't find a way to _unregister_ the CM6 extension...

**Comment by deathau** [comment]
Nevermind, I worked it out! (one has to submit the extension in an array that you keep a reference to and modify that array in place by removing the extension from it — or adding it back when toggled back on)
