### ISSUE TITLE
Can't switch Typewriter Scrolling off after Obsidian upgrade.

### ISSUE THREAD

**Issue by gala8y** [deathau/cm-typewriter-scroll-obsidian#3]
Upgraded Obsidian from v0.9.19 to v0.10.0 and once Toggle Typewriter Scrolling is on, switching it off has no effect. Switching plugin off has also no effect (functionality stays on). Closing Obsidian helps.

**Comment by deathau** [comment]
Thanks for pointing this out. There were some changes to do with how codemirror plugins get loaded, so I'll have to change to that.
In the meantime, reloading after toggling the plugin is a workaround

**Comment by base-I** [comment]
Cmd+R reloads the vault and disables the plugin properly :)
