### ISSUE TITLE
Not really an issue but a feature request: Add Hotkey for turning on and off

### ISSUE THREAD

**Issue by base-I** [deathau/cm-typewriter-scroll-obsidian#4]
Hey,

I love the plugin - sometimes I absolutely hate it, especially for editing longer notes, the page jumps to much I get confused and it breaks my focus.

So: Could you add an option to add a hotkey to turn it on and off quickly :)

(Don't take the "I hate it" to literally, I could not resist describing my experience in such a nice contradicting way. The moments I love the plugin greatly outweigh the times I don't like it so much)

**Comment by deathau** [comment]
There already is! It's just not bound to anything by default. You can find it in the hotkey settings and bind it to whatever key you want.
You can also toggle it via the command panel. `ctrl`+`p`, type "typewriter" and the option should come up.

Note that there is a bug right now with the latest version of Obsidian and the plugin not actually disabling properly (#3)

**Comment by base-I** [comment]
Oh, ok. Thanks. I tried searching for a hotkey, did not find one. Anyway, the not disabling part is fixed by cmd+R, which reloads the vault (?)
