### ISSUE TITLE
More a request than an issue...

### ISSUE THREAD

**Issue by zvtoth** [deathau/cm-typewriter-scroll-obsidian#5]
This is a great plug-in, thank you. 
I was wondering if there is an option to have it turned off as default and be able to toggle it when needed. I love it when writing, but when browsing through notes and copy-pasting it can be a little cumbersome. If I enable the plugin in Obsidian, then it is automatically on in every note I open; I would rather have it off by default and toggle it with a keyboard shortcut. (Now the shortcut only works if it's on by default.)
Regardless, thank you!

**Comment by deathau** [comment]
If you turn the plugin on, then go to the Typewriter Scroll settings and turn it off there (or use the keyboard shortcut to toggle it off), does that work? You just keep the plugin on, but only toggle the keyboard shortcut when you want?

**Comment by zvtoth** [comment]
Ha, it works! I was pretty sure I had tried that. Sorry for the trivial question, and thanks for the help! (And for the plugin.)
