### ISSUE TITLE
Live Preview Table not respecting typewriter offset

### ISSUE THREAD

**Issue by bladeacer** [deathau/cm-typewriter-scroll-obsidian#53]
Unlike this previous [issue](https://github.com/deathau/cm-typewriter-scroll-obsidian/issues/50), it seems that live preview tables does not respect the typewriter offset defined (with typewriter scroll toggled on). It is mildly annoying but bearable for now. 

Either way, thx for making such a great plugin!

Attached is a video of what I am talking about.  

https://github.com/deathau/cm-typewriter-scroll-obsidian/assets/148305363/78f1e360-922c-4c1b-83bb-a7cd335de716

**Comment by luxuxl** [comment]
Have the same problem

**Comment by luxuxl** [comment]
have solved by add a snippet, you can find more detail in other's issue

**Comment by bladeacer** [comment]
which issue specifically?

**Comment by luxuxl** [comment]
Just the one under your issue

https://github.com/deathau/cm-typewriter-scroll-obsidian/issues/50

**Comment by bladeacer** [comment]
ah, I see. thx for clarifying.

**Comment by luxuxl** [comment]
It's still strange in edit table, I change to another plugin named scroll offset,it doesnt have this problem,but it has another bug.
